- label: "JIRA"
  message: "$issuePrefix"
  color: "blue"
  url: "https://loopcrack.atlassian.net/browse/$issuePrefix"
  when: "$issuePrefix"
- label: "PR Size"
  message: "Large"
  color: "red"
  when: "$additions > 400"

- label: "PR Size"
  message: "Medium"
  color: "yellow"
  when: "$additions > 100 && $additions <= 400"

- label: "PR Size"
  message: "Small"
  color: "green"
  when: "$additions <= 100"
