-- MySQL Script generated by MySQL Workbench
-- Tue Sep 26 23:29:17 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Kinub
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Kinub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Kinub` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `Kinub` ;

-- -----------------------------------------------------
-- Table `Kinub`.`email_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categories`;
CREATE TABLE `categories` (
  `categoryId` int NOT NULL AUTO_INCREMENT,
  `categoryName` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `categoryImageId` int NOT NULL,
  `categoryIconId` int NOT NULL,
  PRIMARY KEY (`categoryId`),
  KEY `icon_FK_idx` (`categoryIconId`),
  KEY `image_FK_idx` (`categoryImageId`),
  CONSTRAINT `category_icon_FK` FOREIGN KEY (`categoryIconId`) REFERENCES `files` (`fileId`),
  CONSTRAINT `category_image_FK` FOREIGN KEY (`categoryImageId`) REFERENCES `files` (`fileId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;;

DROP TABLE IF EXISTS `category_tags`;
CREATE TABLE `category_tags` (
  `categoryTagId` int NOT NULL AUTO_INCREMENT,
  `categoryTagName` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `categoryId` int NOT NULL,
  PRIMARY KEY (`categoryTagId`),
  KEY `category_FK` (`categoryId`),
  CONSTRAINT `category_FK` FOREIGN KEY (`categoryId`) REFERENCES `categories` (`categoryId`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;;

DROP TABLE IF EXISTS `certificates`;
CREATE TABLE `certificates` (
  `certificateId` int NOT NULL AUTO_INCREMENT,
  `certificatefileName` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `certificatePreviewId` int NOT NULL,
  `certificatefileId` int NOT NULL,
  PRIMARY KEY (`certificateId`),
  KEY `certificate_file_FK_idx` (`certificatefileId`),
  KEY `certificate_preview_FK_idx` (`certificatePreviewId`),
  CONSTRAINT `certificate_file_FK` FOREIGN KEY (`certificatefileId`) REFERENCES `files` (`fileId`),
  CONSTRAINT `certificate_preview_FK` FOREIGN KEY (`certificatePreviewId`) REFERENCES `files` (`fileId`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;;

DROP TABLE IF EXISTS `email_types`;
CREATE TABLE `email_types` (
  `emailTypeId` int NOT NULL AUTO_INCREMENT,
  `emailTypeName` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`emailTypeId`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;;

DROP TABLE IF EXISTS `emails`;
CREATE TABLE `emails` (
  `emailId` int NOT NULL AUTO_INCREMENT,
  `emailTypeId` int NOT NULL,
  `emailContent` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`emailId`),
  KEY `email_type_FK` (`emailTypeId`),
  CONSTRAINT `email_type_FK` FOREIGN KEY (`emailTypeId`) REFERENCES `email_types` (`emailTypeId`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;;

DROP TABLE IF EXISTS `files`;
CREATE TABLE `files` (
  `fileId` int NOT NULL AUTO_INCREMENT,
  `fileRoute` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `uuid` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `fileName` varchar(45) COLLATE utf8mb4_unicode_ci NOT NULL,
  `fileDirectoryRoute` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`fileId`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;;

DROP TABLE IF EXISTS `home_page`;
CREATE TABLE `home_page` (
  `homePageId` int NOT NULL,
  `aboutUsText` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `aboutUsImageId` int NOT NULL,
  `aboutUsVideoId` int NOT NULL,
  PRIMARY KEY (`homePageId`),
  KEY `about_us_image_FK_idx` (`aboutUsImageId`),
  KEY `about_us_video_FK_idx` (`aboutUsVideoId`),
  CONSTRAINT `about_us_image_FK` FOREIGN KEY (`aboutUsImageId`) REFERENCES `files` (`fileId`) ON DELETE CASCADE,
  CONSTRAINT `about_us_video_FK` FOREIGN KEY (`aboutUsVideoId`) REFERENCES `files` (`fileId`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;;

DROP TABLE IF EXISTS `measurement_solutions`;
CREATE TABLE `measurement_solutions` (
  `msId` int NOT NULL AUTO_INCREMENT,
  `msName` varchar(45) COLLATE utf8mb4_unicode_ci NOT NULL,
  `msIconId` int NOT NULL,
  `msImageId` int NOT NULL,
  `msDescription` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`msId`),
  KEY `measurement_solution_icon_FK_idx` (`msIconId`),
  KEY `measurement_solution_image_FK_idx` (`msImageId`),
  CONSTRAINT `measurement_solution_icon_FK` FOREIGN KEY (`msIconId`) REFERENCES `files` (`fileId`),
  CONSTRAINT `measurement_solution_image_FK` FOREIGN KEY (`msImageId`) REFERENCES `files` (`fileId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;;

DROP TABLE IF EXISTS `product_files`;
CREATE TABLE `product_files` (
  `productsId` int NOT NULL,
  `filesId` int NOT NULL,
  `fileType` enum('image','video','product certificate','datasheet','brochure','user manual') COLLATE utf8mb4_unicode_ci NOT NULL,
  `pfId` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`pfId`),
  KEY `fk_products-files_products1_idx` (`productsId`),
  KEY `fk_products-files_files1_idx` (`filesId`),
  CONSTRAINT `file_FK` FOREIGN KEY (`filesId`) REFERENCES `files` (`fileId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `product_file_FK` FOREIGN KEY (`productsId`) REFERENCES `products` (`productId`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;;

DROP TABLE IF EXISTS `product_tags`;
CREATE TABLE `product_tags` (
  `productTagId` int NOT NULL AUTO_INCREMENT,
  `productTagName` varchar(45) COLLATE utf8mb4_unicode_ci NOT NULL,
  `producTagId` int NOT NULL,
  PRIMARY KEY (`productTagId`),
  KEY `product_FK_idx` (`producTagId`),
  CONSTRAINT `product_tag_FK` FOREIGN KEY (`producTagId`) REFERENCES `products` (`productId`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;;

DROP TABLE IF EXISTS `products`;
CREATE TABLE `products` (
  `productId` int NOT NULL AUTO_INCREMENT,
  `productName` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `productModel` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `productDescription` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `productTechnicalInfo` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `productDemoVideoId` int NOT NULL,
  `productCategoryId` int NOT NULL,
  PRIMARY KEY (`productId`),
  KEY `product_category_FK_idx` (`productCategoryId`),
  KEY `demo_video_FK_idx` (`productDemoVideoId`),
  CONSTRAINT `demo_video_FK` FOREIGN KEY (`productDemoVideoId`) REFERENCES `files` (`fileId`),
  CONSTRAINT `product_category_FK` FOREIGN KEY (`productCategoryId`) REFERENCES `categories` (`categoryId`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;;

DROP TABLE IF EXISTS `products-category_tags`;
CREATE TABLE `products-category_tags` (
  `products_id` int NOT NULL,
  `tags_id` int NOT NULL,
  `pfId` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`pfId`),
  KEY `fk_products-tags_products1_idx` (`products_id`),
  KEY `fk_products-tags_tags1_idx` (`tags_id`),
  CONSTRAINT `product_Id` FOREIGN KEY (`products_id`) REFERENCES `products` (`productId`) ON DELETE CASCADE,
  CONSTRAINT `tag_id` FOREIGN KEY (`tags_id`) REFERENCES `category_tags` (`categoryTagId`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;;

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `userId` int NOT NULL AUTO_INCREMENT,
  `userFirstName` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `userLastName` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `userEmail` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `userPassword` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `userToken` varchar(13) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `confirmed` tinyint DEFAULT NULL,
  `isAdmin` tinyint DEFAULT NULL,
  PRIMARY KEY (`userId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;;

INSERT INTO `email_types` (`emailTypeId`, `emailTypeName`) VALUES
(1, 'contacto'),
(2, 'soporte tecnico'),
(3, 'info producto');

INSERT INTO `files` (`fileId`, `fileRoute`, `uuid`, `fileName`, `fileDirectoryRoute`) VALUES
(1, '/assets/images/auth-one-bg.jpg', '79c4387d-c1cb-4e6f-b418-8c391d852e2c', 'auth-one-bg.jpg', '/assets/images/'),
(2, '/assets/images/drop.svg', '9d7b76e0-a31f-4e0f-9ac6-b71bc35f2ed4', 'drop.svg', '/assets/images/');



/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;